import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router"
import { getSession, useSession } from "next-auth/react";
import HomeLayout from "layout/HomeLayout";

export default function Home({ session }) {
  const router = useRouter();
  // const { data: session, status } = useSession();
  // console.log(session, status);

  // useEffect(() => {
  //   if (router.pathname === "/") {
  //     document.title = "Inicio - Evernote Clone";
  //   }
  // }, []);

  // if (status === "loading") {
  //   return <div>Loading...</div>;
  // }

  // if (status === "unauthenticated") {
  //   router.push("/login");
  // }

  return (
    <>
      {session ? (
        <div className="grid place-content-center h-screen">
          <Head>
            <title>Evernote Clone - Sebastian Silva</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <HomeLayout />
        </div>
      ) : (
        <p>skeleton....</p>
      )}
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const session = await getSession(ctx);
  if(!session) return {
    redirect: {
      destination: '/login',
      permanent: false,
    }
  }
  return {
    props: {
      session,
    },
  };
};
